{{- if and .Values.serviceAccount.create .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "elasticsearch-curator.serviceAccountName" .}}
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  labels:
    app: {{ template "elasticsearch-curator.fullname" . }}
    chart: {{ template "elasticsearch-curator.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}

